### ISSUE TITLE
Cache loaded elements

### ISSUE THREAD

**Issue by astrauka** [babotech/react-ingrid#11]
I am using lazy loading - when element is visible for 0.5 seconds, then I load image.
When I scroll down, I see images loading.
When I scroll up, I believe the images are loaded and should be in place.
Instead I see them loading.
Expected behavior - either cache rendered content and display it on scrolling back or allow specifying height of elements to be loaded in advance
![example](https://cloud.githubusercontent.com/assets/1308928/15404804/e706fc6c-1e07-11e6-9f00-1bb8fc2a934f.gif)
@galkinrost

**Comment by galkinrost** [comment]
Hi, @astrauka! I think you use local state of your item component to store information was an image loaded or not, do you?

**Comment by astrauka** [comment]
@galkinrost yes, I can, but I have added the empty div instead of image to safe on performance as scrolling DOM up will try to load images on scroll and that looks sluggish.

I also thought of an option of storing the items html in the state but that sounds awkward.

**Comment by astrauka** [comment]
@galkinrost could you elaborate on the fix? ^^

**Comment by galkinrost** [comment]
The problem was that we need to render all items for server rendering before componentDidMount. But for browser we should render only visible items. After my fix you could remove your lazy loading and images will load only when they will be visible. So please try it now and give me know please

**Comment by galkinrost** [comment]
@astrauka does it solve your issue?

**Comment by astrauka** [comment]
Well :) Not exactly
![dom_grid svg](https://cloud.githubusercontent.com/assets/1308928/15461878/3a0fdc0a-20c7-11e6-8fbf-f7d4da37b5d3.png)
I was willing to have an option to define how much height the items should be persisted.
So as per image we have total grid container height, then materialized (persisted) in DOM height and the browser window visible items height.
I wanted to tell that materialized DOM should take:
5000px backwards and
800px forward
Such that the items would not be destroyed once they go out of visible frame.

But I think that my case might be an edge case and maybe not worth implementing?

**Comment by galkinrost** [comment]
I`m trying understand why you need it. If you want images start loading only when they're visible, after my latest commit they will do it without any lazy loading implementation. However if you want to do it, I think you should store what images were loaded and then display them without delay

**Comment by astrauka** [comment]
@galkinrost agree with "you should store what images were loaded and then display them without delay"
